# Generated by Django 2.2.4 on 2019-10-16 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(help_text='Ingrese código de la asignatura.', unique=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(1)], verbose_name='Código asignatura')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la asignatura.', max_length=40, verbose_name='Nombre de la asignatura')),
                ('año', models.PositiveIntegerField(help_text='Ingrese el año en el que se cursa la asignatura.', validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)], verbose_name='Año de la asignatura')),
            ],
            options={
                'verbose_name_plural': 'asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('dni', models.PositiveSmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)])),
                ('nombre', models.CharField(help_text='Ingrese el nombre del profesor.', max_length=40)),
                ('apellido', models.CharField(help_text='Ingrese el apellido del profesor.', max_length=40)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
    ]
