# Generated by Django 2.1.1 on 2019-10-28 18:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(help_text='Ingrese código de la asignatura.', unique=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(1)], verbose_name='Código asignatura')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la asignatura.', max_length=40, verbose_name='Nombre de la asignatura')),
                ('año', models.PositiveIntegerField(help_text='Ingrese el año en el que se cursa la asignatura.', validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)], verbose_name='Año de la asignatura')),
            ],
            options={
                'verbose_name_plural': 'asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('dni', models.PositiveSmallIntegerField(help_text='Ingrese el DNI del profesor.', primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(1)])),
                ('nombre', models.CharField(help_text='Ingrese el nombre del profesor.', max_length=40)),
                ('apellido', models.CharField(help_text='Ingrese el apellido del profesor.', max_length=40)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha actual')),
                ('turno', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=6)),
                ('curso', models.PositiveIntegerField(help_text='Ingrese el curso correspondiente.', validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)], verbose_name='Curso perteneciente')),
                ('division', models.PositiveIntegerField(help_text='Ingrese la division del curso correspondiente.', validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)], verbose_name='Division del curso')),
                ('ausente', models.BooleanField(blank=True, null=True)),
                ('tarde', models.BooleanField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(help_text='Elegir una asignatura', on_delete=django.db.models.deletion.CASCADE, to='autoridades.Asignatura')),
                ('profesor', models.ForeignKey(help_text='Elegir un profesor', on_delete=django.db.models.deletion.CASCADE, to='autoridades.Profesor')),
            ],
            options={
                'verbose_name_plural': 'Seguimiento',
            },
        ),
    ]
